### ISSUE TITLE
Detailansicht: Möglichkeit zum Melden von Fehlern in der Beschreibung

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#11]
Der Benutzer soll die Möglichkeit erhalten Fehler zu melden. z.B. falsche Öffnungszeiten
Im einfachsten Fall öffnet sich eine E-Mail, ähnlich der "alten" Berlin Vegan App.

**Comment by ces92** [comment]
Hier soll es eigentlich um Fehler bei den Geschäften und Co. gehen und nicht um die der App oder?

**Comment by jmastr** [comment]
Das ist richtig. Du kannst dir zum Vergleich mal die alte App angucken. Habe das einfach nur nach implementiert. Man kann aber bestimmt die Texte noch verbessern und Informationen (siehe #14) hinzufügen oder entfernen.
