### ISSUE TITLE
Detailansicht: Melden von Fehlern: Mehr Infos zum Programmstatus hinzufügen

### ISSUE THREAD

**Issue by jmastr** [Berlin-Vegan/berlin-vegan-guide#14]
Für Issue #11 wurde dem User die Möglichkeit gegeben eine vorformulierte Mail zu verfassen, um einen Fehler in der Beschreibung/den Details mitzuteilen. Dazu werden folgende Informationen zum Programmstatus generiert, z.B.:

---

App Version: development-7d52576
Device Name: Nexus 5
Platform: Android
Device Version: 5.1.1

---

Die alte App hat zusätzlich noch Informationen zu GPS/Location Stati.

**Comment by smeir** [comment]
Ich glaube die aktuellen Daten reichen erstmal aus. Die alte App hatte die Location Stati, da es immer wieder zu Problemen kam.

Vor kurzem habe ich noch die "Flavors" hinzugefügt, damit wissen wir dann ob die E-Mail von einer Playstore Version oder F-Droid kommt.
