### ISSUE TITLE
Erste Entwürfe

### ISSUE THREAD

**Issue by Robin-siebzehn3** [Berlin-Vegan/berlin-vegan-guide#17]
Hi ihr Lieben,

hier die ersten Entwürfe für das neue Design der App :)
Ich habe einfach erstmal gemacht, ihr könnt ja alle mal drüber schauen und sagen, was euch auf-, ein- und missfällt ;) Alle bisherigen Funktionen sollten drin sein und ich hab versucht, alle besprochenen Dinge vom letzten Treffen mit einzubeziehen. Allerdings kann ich mich nicht mehr erinnern, worum es zum Schluss zum Thema Listen- und Kartenansicht in der Sidebar (wie heißt die richtig??) ging.
Eine Frage noch: Wie habt ihr dieses Raster bei euch auf den Geräten angeschaltet? Ich kam jetzt erstmal so ganz gut ohne klar, aber für die Zukunft wäre das ja sicher ganz hilfreich.

Freu mich auf euer Feedback!
Robin

![1-liste-1_uebersicht-150614](https://cloud.githubusercontent.com/assets/12401165/8157620/35324a6c-1356-11e5-90a1-5b0ccfd8b084.png)
![1-liste-2_suche-150614](https://cloud.githubusercontent.com/assets/12401165/8157621/353be4d2-1356-11e5-9c2f-46c4f8b75fcc.png)
![1-liste-3_sidebar-150614](https://cloud.githubusercontent.com/assets/12401165/8157622/3543993e-1356-11e5-9e1d-1f8a7eb0ef58.png)
![2-karte-1_sidebar-150614](https://cloud.githubusercontent.com/assets/12401165/8157624/35540ce2-1356-11e5-94d5-276b0c032f5c.png)
![2-karte-2_uebersicht-150614](https://cloud.githubusercontent.com/assets/12401165/8157625/355620e0-1356-11e5-8633-7dd24be7ab69.png)
![3-details-150614](https://cloud.githubusercontent.com/assets/12401165/8157623/35530a40-1356-11e5-8958-9a90f5a9553c.png)
![4-lage-150614](https://cloud.githubusercontent.com/assets/12401165/8157626/355dada6-1356-11e5-8353-83b3acb65cbf.png)
![5-details-komplett-150614](https://cloud.githubusercontent.com/assets/12401165/8157627/3562598c-1356-11e5-990f-7ffe8ab057b5.png)

**Comment by jmastr** [comment]
Moin,

das sieht schon sehr gut aus! Für den ersten Screen hätte ich gerne noch den Favoriten-Stern:

![screen](https://cloud.githubusercontent.com/assets/11860038/8160295/b82ef880-136e-11e5-9d04-c406ccb30f39.png)

Was sagen die Anderen dazu?

**Comment by jmastr** [comment]
Die Sidebar heißt 'Navigation Drawer'. Das Raster kriegt man mit der App 'Keyline Pushing' (https://play.google.com/store/apps/details?id=com.faizmalkani.keylines&hl=de).

**Comment by smeir** [comment]
Ja, dank für die ganzen Vorschläge. Ich glaube aber das wird schwierig in einem Ticket alle Screen zu diskutieren. Ich hätte da lieber einzelne Tickets oder andere Platformen wie dribble.com. Oder beim nächsten Meeting, vielleicht geht es dort sogar am besten. Ansonsten befürchte ich das es sehr schnell unübersichtlich wird. Vor allem wenn das Robin auch noch Änderungen vornimmt.

**Comment by Robin-siebzehn3** [comment]
So, habe jetzt alle hier zu findenden Screens in Einzel-Issues aufgeteilt für eine bessere Übersicht. Braucht jemand den Issue hier noch? Ansonsten würde ich ihn der Vollständigkeit und Übersichtlichkeit halber einfach löschen.

**Comment by smeir** [comment]
ja, kannst du schließen.
