### ISSUE TITLE
Abbrechen der Standorterkennung

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#22]
Es sollte möglich sein die Standorterkennung beim Programmstart abzubrechen. Die Liste wird dann in der "Default-Sortierung" angezeigt.

**Comment by IncorporateApps** [comment]
Dann muss es aber möglich sein, dass der GPS Standort im Hintergrund weiterhin ermittelt werden und wir brauchen dann eine Sortierung nach Standort

**Comment by smeir** [comment]
Wir haben ja den Refresh-Mechanismus, ich denke den sollten wir dafür nehmen nochmal die Standorterkennung zu aktivieren. Ich glaube dies geschieht jetzt auch schon so.

**Comment by IncorporateApps** [comment]
Finde ich nicht so gut, besonders wenn man bedenkt, dass wir den Pfeil um die Texterweiterung erklären mussten, kommt keiner drauf, dass nach einem Refresh nach Standort sortiert wird. Besonders dann nicht, wenn der Benutzer schon die Standartsuche unterbrochen hat.

**Comment by IncorporateApps** [comment]
Und da der Standort nicht sofort verfügbar ist, wird er wird 20 Sekunden oder so warten müssen und wieder unterbrechen.

**Comment by smeir** [comment]
Durch #34 und #35 brauche ich persönlich jetzt keinen Abbrechenbutton mehr. :-)

**Comment by ces92** [comment]
Ich mach das erst Mal zu... Wenn es wirklich gebraucht wird, kann es wieder aufgemacht werden.
