### ISSUE TITLE
Listenansicht (geschlossen, schliesst bald)

### ISSUE THREAD

**Issue by Robin-siebzehn3** [Berlin-Vegan/berlin-vegan-guide#23]
Hier nochmal der erste Entwurf vom 15. Juni 2015:
![1-liste-1_uebersicht_klein](https://cloud.githubusercontent.com/assets/12401165/9023063/9cc275ac-388c-11e5-8847-1830d6a95370.png)
![1-liste-2_suche_klein](https://cloud.githubusercontent.com/assets/12401165/9023064/9cc71238-388c-11e5-9df0-8aca22690cd3.png)

**Comment by Robin-siebzehn3** [comment]
Hier zwei Vorschläge für die Darstellung von geschlossenen oder bald schließenden Einrichtungen. Ich sehe an der Stelle ehrlich gesagt kein Icon, die Lösung von Dresden Vegan finde ich auch nicht wirklich den Hit. Die machen ja hinter JEDE Einrichtung nen Schild, was das Ganze total unruhig macht. Außerdem ist es ja, wenn die Einrichtung geschlossen ist, etwas negatives und wir wollen diese ja eher in den Hintergrund rücken lassen. Ein Icon würde dieses Feld jedoch auffälliger gegenüber der anderen machen und in den Vordergrund rücken.
Da "derzeit geschlossen" noch ein bisschen länger ist, als "schließt um XX Uhr!", habe ich einfach mal das gemacht, anstatt einfach "schließt bald!". Fand ich noch ein Stück benutzerfreundlicher und der User spart sich einen Klick in die Details.
Vielleicht als Tipp für die Programmierung: Version 1 würde den Text in derselben Schriftgröße wie auch die anderen kleinen Texte schreiben. Version 2 schreibt den Text kleiner (ich habe 21 auf 20 pt) (so ist mehr Platz für den Namen der Location), der Text steht mittig über der Entfernungsangabe. Ist das so umsetzbar? Farbe für das Rot ist #ff5252

Was meint ihr?
![closed-und-closing_v1a_klein](https://cloud.githubusercontent.com/assets/12401165/9023069/d9d510bc-388c-11e5-80fa-96357f206bf0.png)
![closed-und-closing_v1b_klein](https://cloud.githubusercontent.com/assets/12401165/9023070/d9da1d14-388c-11e5-8f81-918fdfef35c8.png)

**Comment by smeir** [comment]
Ja, schwierig. Ich vote mal für die Variante mit kleiner Schrift, ansonsten wird es wirklich eng mit den Restaurantnamen. 
Im Moment sieht es danach aus, das du die geschlossene Restaurants noch grau einfärbst. Ich denke das wäre keine so gute Idee. Grau steht immer für "Disabled" und sieht so aus das man es nicht anklicken kann. Ich glaube der rote Hinweis "derzeit geschlossen" ist eine ausreichende Markierung.

**Comment by Robin-siebzehn3** [comment]
Wie besprochen würde ich das "derzeit geschlossen" grau machen und ich denke, es macht auch Sinn, zusätzlich die km-Angabe dann nicht grün zu lassen sondern auch auszugrauen.
![closed-und-closing_v2_klein](https://cloud.githubusercontent.com/assets/12401165/9038467/be24ed06-39f4-11e5-9098-947b768e39ba.png)
