### ISSUE TITLE
Navigation Drawer

### ISSUE THREAD

**Issue by Robin-siebzehn3** [Berlin-Vegan/berlin-vegan-guide#24]
Hier nochmal die ersten Entwürfe vom 15. Juni 2015 vom Navigation Drawer in der Listenansicht und der Kartenansicht. Ich denke, dafür ist ein Ticket praktischer.
![1-liste-3_navdraw_klein](https://cloud.githubusercontent.com/assets/12401165/9023051/4d35c426-388c-11e5-91de-5deda6e3dffa.png)
![2-karte-1_navdraw_klein](https://cloud.githubusercontent.com/assets/12401165/9023053/502f799c-388c-11e5-80f2-1bec4ee8d538.png)

**Comment by smeir** [comment]
Vorschlag für die Einträge im NavDrawer (erste Version)
- "Essen und Trinken" alternativ "Gastronomie"
- Einkaufen
- Favoriten
- Einstellungen
- Über

**Comment by ces92** [comment]
Done
