### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by Robin-siebzehn3** [Berlin-Vegan/berlin-vegan-guide#26]
Hier nochmal die ersten Entwürfe vom 15. Juni 2015. Einmal komplett und einmal die erste Ansicht. 
![5-details-komplett_klein](https://cloud.githubusercontent.com/assets/12401165/9022973/cb256d58-3889-11e5-9cfa-8368c8643f77.png)
![3-details_klein](https://cloud.githubusercontent.com/assets/12401165/9022974/cb2ea8be-3889-11e5-9aff-d7488e451a53.png)

**Comment by Robin-siebzehn3** [comment]
Hier zwei Versionen der überarbeiteten Detail-Ansicht. Das graue Feld unten bei Version 2 soll natürlich da nicht hin, ich habe es nur gelassen, damit beide Dateien gleich hoch sind und sie besser vergleichbar sind.
Version 1 ist jetzt noch mit der Karte bzw dem zukünftigen Vorschaubild, so wie es dann mal sein sollte. Version 2 ist demnach erstmal ohne. Als Navigations-Icon habe ich jetzt Icon "navigation" ( ;) ) benutzt. Ich habe auch gesehen, dass als Favorit-Icon eigentlich eher ein Herz genommen wird. Sollen wir das mal auch umstellen? Es heißßßßßt, naaaa? Richtiiig: Icon "favorite" ;) Bzw. "favorite border"
Den Infotext würde ich lieber wieder gerade stellen. Die Texte sind ja teilweise ziemlich lang, da finde ich, geht kursiv schnell auf die Augen.
Die Frage jetzt bei der Fettung der Öffnungszeiten des aktuellen Tages: Wenn die Location angenommen am Montag von 17 bis 2 Uhr auf hat. Was wird dann am "quasi" ja schon Dienstag ab 0 Uhr gefettet? Dienstag? Oder immernoch Montag?
Ansonsten habe ich mal die sonstigen Infos sortiert. Ich hoffe, es ist mir gelungen, eine für die Allgemeinheit richtige Reihenfolge der Wichtigkeiten zu finden?
Und wie besprochen auch ein edit-Icon hinter den Angaben, die vom System als "unbekannt" ausgespuckt werden.
![3-details_v2a_klein](https://cloud.githubusercontent.com/assets/12401165/9022994/370e9e54-388a-11e5-86c0-6c9d86b77cc7.png)
![3-details_v2b_klein](https://cloud.githubusercontent.com/assets/12401165/9022995/3715a758-388a-11e5-9c8d-4504a3d9c775.png)

**Comment by smeir** [comment]
1) Die Fettung der Öffnungzeiten nach 0 Uhr ist in der Tat schwierig. Wie man es macht ist es wahrscheinlich falsch. Im Moment wir der aktuelle Tag fett eingefärbt, besser wäre natürlich die Zeile fett darzustellen, die auch relevant ist.

2) Frage: Was passiert mit dem großen Anruf und Webseite Buttons wenn die Daten nicht vorliegen? Ausgrauen?

3) das Edit Icon für einzelne Felder können wir im Moment nicht umsetzen. Das Icon natürlich schon, aber nicht die Logik dahinter. Von daher erstmal nur das Edit Icon am Ende.

4) das Icon mit den 3 Punkten untereinander müssen wir noch austauschen denke ich. Damit wird üblicherweise ein Popup Menu assoziert wie es viele Apps oben rechts haben.

**Comment by Robin-siebzehn3** [comment]
1) Wie ist es denn mit der Anzeige in der Liste? Wenn Montag von 17 bis 2 Uhr auf ist, zeigt er dann Dienstag ab 0 Uhr an, dass die Location geschlossen ist? Weil es ist ja quasi Dienstag 0 Uhr und da steht ja an sich, dass sie zu hat.

2) Ausgrauen würde ich machen ja. Der Grauwert ist #b6b6b6

4) Also das Icon mit den 3 vertikalen Punkten heißt "more vert". Wir können aber auch das "more horiz" nehmen, also Punkte nebeneinander. Macht Maps auch so. Ich fand nur vertikale Punkte schöner, weil sie optisch mehr der Liste entsprechen.

**Comment by smeir** [comment]
1) in der Liste zeigt die App im Moment alles korrekt an (im Moment aber noch ohne Uhrzeit). Also in deinem Beispiel wäre es um 1 Uhr noch offen.

4) Ja, aber in Maps kann man darauf klicken und es klappt dann auf. In der BV App kann man nicht auf die Icons klicken, soweit ich weiss.

**Comment by Robin-siebzehn3** [comment]
4) Macht das für die Logik des Icons einen Unterschied, ob die Infos dahinter ausklappbar sind oder nicht? Sonst können wir auch Icon "info" nehmen. Da würde ich aber dann die Version "outline" favorisieren.
