### ISSUE TITLE
Icon für Einrichtungen mit rein veganem Angebot

### ISSUE THREAD

**Issue by Robin-siebzehn3** [Berlin-Vegan/berlin-vegan-guide#28]
Hier zwei Vorschläge für das Icon für Einrichtungen mit rein veganem Angebot: Einmal (angelehnt an die Veganblume und generell ja auch ein schon sehr etabliertes Symbol dafür) ein Blatt und ein Kreis mit einem "v" darin. Damit ihr euch das besser vorstellen könnt, habe ich es gleich mal in die Listenansicht eingebaut.
![100provegan_v1](https://cloud.githubusercontent.com/assets/12401165/9023031/901680f6-388b-11e5-8aff-3b49f4b402c3.png)

**Comment by smeir** [comment]
ich vote für das (v) :-)

**Comment by IncorporateApps** [comment]
V

**Comment by Robin-siebzehn3** [comment]
Also wenn es das "v" dann sein soll, anbei die Datei. Ich habe sie jetzt so angelegt wie alle anderen Icons. Die Benennung fügt sich da auch ein. Wenn das aber keinen Sinn machen sollte, könnt ihr die Datei auch gerne umbenennen ;) Braucht ihr das Icon auch noch in anderen Größen oder reicht die (ich glaube) größte? 
![ic_100provegan_black_48dp](https://cloud.githubusercontent.com/assets/12401165/9038756/09f2e592-39f7-11e5-9c1c-d3c953c42b0f.png)

**Comment by Robin-siebzehn3** [comment]
Hallo, hier nochmal das Icon in/mit den besprochenenen Spezifikationen/Anpassungen. Danke!
![ic_100provegan_black_18dp](https://cloud.githubusercontent.com/assets/12401165/9180236/86612512-3fa1-11e5-8408-f4c4e3c701b0.png)

**Comment by smeir** [comment]
ist hinzugefügt
