### ISSUE TITLE
Gastronomie: erweiterte Filter

### ISSUE THREAD

**Issue by Robin-siebzehn3** [Berlin-Vegan/berlin-vegan-guide#29]
So, hier die Filteranzeige. Wie besprochen: Oben, rechts neben dem Suchen-Icon wird das Icon "filter list" angezeigt. Beim Klicken darauf öffnet sich ein Menü. Ich bin ehrlich gesagt etwas unglücklich damit - die Liste ist doch ziemlich lang und von daher müsste sie scrollbar werden...
Sollen wir nicht doch nochmal darüber nachdenken, die Filterfunktion mit den den Navigation Drawer aufzunehmen und dort so etwas wie ein neues Einstellungen-Fenster einzusetzen? Finde ich wie gesagt echt aufgeräumter. Oder man lässt das Icon dort, macht es aber so, dass sich trotzdem ein komplett neues Fenster öffnet.
![filter_v1_1geschlossen_klein](https://cloud.githubusercontent.com/assets/12401165/9023013/c7e5a79c-388a-11e5-87a0-7eaad5c16aa8.png)
![filter_v1_2geoeffnet_klein](https://cloud.githubusercontent.com/assets/12401165/9023014/c7f70ce4-388a-11e5-9082-f9986eb47ce0.png)

**Comment by smeir** [comment]
In dem Screenhost sieht es jetzt so aus, das es ein Popup Fenster ist. Das ist in der Tat schwierig zu navigieren gerade mit Scrollbar. War nicht die Idee das wir das als eher so wie einen "Navigation Drawer" machen, nur halt auf der rechte Seite. Vorteil wäre das man sofort die Veränderung in der Listenansicht sieht. Also so ein bisschen wie bei der Wikipedia App. Dort gibt es auch 2 "Navigation Drawer". Sieht dann so aus. https://lh5.ggpht.com/y0QdFSNYhZl_573t5KkJX1eFN9SdKTJps0K0SWf_EJzp66V6nx7hRI84fMFADYGTnMM=h900-rw

**Comment by Robin-siebzehn3** [comment]
Ich hatte in den Guidelines nichts gefunden, was so einen rechten Navigation Drawer "erlaubt" oder gleichkommt... Dieses Popup gibt es aber. Die "rechte Navigation Drawer" bei WIkipedia und die gesamte Wikipedia-App sind ja auch fast gar nicht am Google Design orientiert...
Außerdem wäre der rechte NavDraw dann ja auch scrollbar. Macht dann nicht wirklich nen Unterschied, oder? Optisch zumindest. Technisch schon?

**Comment by smeir** [comment]
Die Navigation ist im Popup ist schwierig, da ja wenn man daneben klickt das Popup weg ist. Und Scrolling gibt es normalerweise auch nicht im Popup. 
Du hast recht eine rechten "Navigation Drawer" gibt es normalerweise nicht, aber verboten ist er sicherlich auch nicht. :-) Vielleicht probieren wir beides einfach mal aus und schauen dann was sich besser anfühlt.

**Comment by Robin-siebzehn3** [comment]
Der rechte NavDraw würde dann so aussehen. Übrigens hatte ich in meinem Browser letztens gesehen, dass Popups doch scrollbar sein dürfen. Vom Feeling her kam mir das, als ich das so gesehen habe, auch nicht komisch vor.
![filter_v2_klein](https://cloud.githubusercontent.com/assets/12401165/9038378/0c79ee44-39f4-11e5-87e8-91b1132dc36f.png)
![screenshot_2015-08-03-15-20-49](https://cloud.githubusercontent.com/assets/12401165/9038379/0c7d38f6-39f4-11e5-8375-de216fa038a1.png)

**Comment by smeir** [comment]
Stimmt, die Popup-Menus sind scrollbar, wenn es viele Optionen gibt. Ich denke wir werden das dann erstmal als Popup ausprobieren.
