### ISSUE TITLE
Hauptansicht: erweiterte Filter für Restaurant/Imbiss

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#3]
- alle
- nur vegetarische
- nur vegane

---
- Bio
- Rohlstuhl
- Hund erlaubt

**Comment by IncorporateApps** [comment]
Hier würde ich zusätzlich vegetarisch + vegan als noch 1 Filter nehmen.
Wir müssten auch in der Liste die Läden irgendwie auch unterscheiden können - 
Icon Vorschläge? - Blatt, Ei+Milch, Omni?

**Comment by smeir** [comment]
Die Idee ist das "nur vegetarische" auch die veganen mit anzeigt. Sie wie "alle" auch die veganen mit anzeigt. 
Ja, in der Liste kann man sicherlich noch einige Informationen anzeigen. 
z.B. ob noch offen, Art der Lokalität, ob es vegan ist usw. Wir müssen aber aufpassen, das wir nicht zu viele Infos werden. Es gibt ja auch noch die Detailansicht. :-)

**Comment by IncorporateApps** [comment]
So viele infos sind es auch nicht, besonders wenn die Bilder kommen, wird es mehr Platz geben.

Ich würde diese hinzufügen:
- Title + Anschrift (untereinander)
- noch geöffnet (icons gibt es im Internet kostenlose)
- Vegan, vegetarisch usw - icons?
- Art, vielleicht auch mal ein Icon?
- Favoriten Stern, clickable.

**Comment by smeir** [comment]
Vegan icon ist jetzt vorhanden, anzeige von "geschlossen/geöffnet" auch. Den Rest des Tickets (Filter) wird in #29 bearbeitet.
