### ISSUE TITLE
Entfernungsanzeige in der Listenansicht ist ungenau

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#31]
ungefähr 20% niedriger, wie der Wert den Google Maps bei Fußgängernavigation anzeigt.

**Comment by ces92** [comment]
das liegt daran, das die Berechnung Luftlinie ist in der App

**Comment by smeir** [comment]
meine Idee wäre einfach 20% mehr anzuzeigen. Zu mindestens für Berlin liefert das gute Ergebnisse. Wenn die App auch mal in anderen Kontexten verwendet wird, müsste man sich natürlich etwas schlaueres einfallen lassen.

**Comment by ces92** [comment]
oder wir schreiben "Luftlinie"

**Comment by IncorporateApps** [comment]
Es gibt ein Paar Routing Libraries, die dies erledigen. Am Besten eine fertige Lib nehmen, wie hier
https://github.com/jd-alexander/Google-Directions-Android

**Comment by jmastr** [comment]
Ich werde es mal mit [YOURS](http://wiki.openstreetmap.org/wiki/YOURS) versuchen. Man bekommt ein geoJSON zurück mit der totalen Distanz. Leider haben die, wie viele andere auch, keine `https` Schnittstelle.

Was auf jeden Fall klar sein dürfte, ist, dass man pro Location eine Anfrage stellen muss. Allerdings vermutlich nur für die, die gerade in dem View liegen +-10 (ungefähr, kümmert sich Android drum).
