### ISSUE TITLE
Vorausplanung ermöglichen (Angabe eines Ausgangspunktes)

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#32]
Im Moment werden die Lokalitäten abhängig vom aktuellen Standpunkt angezeigt. Praktisch wäre, vor allem für Touristen, wenn es möglich ist den Ausgangspunkt festzulegen und so schon vor der Reise die Umgebung zu erkunden.

**Comment by Robin-siebzehn3** [comment]
Nicht nur Touristen. Ich brauche das auch unbedingt! :)
Steht schon fest, wie das aussehen soll? Über einen Menüpunkt, in dem man die Adresse angeben kann und dann die Liste angezeigt bekommt oder tatsächlich dann schon über die Karte, auf der alle Locations bepint sind?

**Comment by ces92** [comment]
Ich würde vorschlagen, dass mit #25 zu kombieren

**Comment by smeir** [comment]
Ich denke es macht für die Listenansicht und auch die Karte Sinn. Später dann auch für "Einkaufen" oder ähnliches. Wie wir das visuell gestalten müssen wir noch überlegen. Ich könnte mir vorstellen,da wir im zuküntigen rechten "Drawermenu" den Punkt haben "Standort festlegen". Dieser gilt dann in der ganzen App solange bis es ausgeschaltet wird oder die App neu startet.

**Comment by smeir** [comment]
Ich glaube wenn wir die Karte haben dann brauchen wir das Feature nicht mehr. Ich würde vorschlagen wir implementieren erstmal die Kartenansicht und schauen dann ob noch Featurewünsche diesbezüglich reinkommen.
