### ISSUE TITLE
Favoritenverwaltung

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#4]
- auf der Detailseite Favoritenmarkierung
- Favoritenverwaltung/Übersicht also extra Activity, Auswahl über Navigation Drawer

**Comment by IncorporateApps** [comment]
Hier vielleicht auch mal ein Stern bei der Listenansicht zur Anzeige ob es ein Favorit ist und zusätzliche Auswahl? Filtern nach 
https://developer.android.com/design/material/images/list_mail.png

Filtern nach Favoriten im Filter anstatt Navigation Drawer oder als icon im Toolbar??

**Comment by smeir** [comment]
Ich finde die aktuelle Lösung über den Filter wirklich sehr gut gelöst. Ob wir Favoriten auch in die Listview als Icon mit aufnehmen entscheiden wir später denke ich. Da macht @Robin-siebzehn3  uns ja vielleicht noch einen Vorschlag. :-)
