### ISSUE TITLE
Verwendung von Android 6.0 permissions

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#41]
Seit Android 6 ist es möglich die Zugriffsrechte erst zur Laufzeit abzufragen. Dies vereinfacht die Installation und die Rechte sind einem Kontext zugeordnet. 

Implementierung:
Entweder direkt verwenden oder über einen wrapper: https://github.com/hotchemi/PermissionsDispatcher

**Comment by ces92** [comment]
Ich hab die App mal im Simulator unter Android 6 getestet, sie stürzt nicht ab und funktioniert erstaunlich stabil, es ist vermutlich gar nicht so viel zu ändern.

**Comment by smeir** [comment]
Ja, sie funktioniert. Ansonsten hätte ich es schon behoben :-),  da ich ja 6.0 auf dem Handy habe. Hier geht es ja eher um Features.
