### ISSUE TITLE
Suche

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#5]
- Icon in der Toolbar
- durchsucht Namen und Beschreibung
- neue Activity, Ergebnisse als Liste, ähnlich der Hauptansicht

**Comment by IncorporateApps** [comment]
Hier sollten wir lieber einfach den Cursor neu initialisieren anstatt neue Activity zu starten.

**Comment by smeir** [comment]
Ja, wäre auch eine Idee.

**Comment by jmastr** [comment]
Habe schon prototypisch etwas implementiert. Bin dabei aber auf folgendes Problem gestoßen: Soll immer die ganze Liste durchsucht werden oder "nur" die schon vorgfilterte, z.B. nur vegane Restaurants. Ersteres hätte den Nachteil, dass es den User verwirren könnte, letzteres, dass ein User vielleicht nicht die gesuchte Gastro Location findet, weil der Filter eingestellt ist.

Wenn man durch verschiedene Symbole den gesetzten Filter in der Toolbar anzeigen würde, wäre der das Suchen nur in der gefilterten Liste nicht ganz so schlimm. Was meint ihr?

**Comment by IncorporateApps** [comment]
Meiner Meinung nach sollte man nur das ersuchen, was angezeigt ist. Wenn neben des Titels auch die Symbole für vegan oder vegetarisch angezeigt werden, sollte dies ein klarer Hinweis sein.

So wie ich die "User" kenne, wird sich, egal was man macht, ein verwirrter immer finden...Ich finde man sollte die App nicht von Funktionalität berauben (wie die Einstellungssache für den Filter) nur weil der eine oder der andere User mit einer Nokia 3310 besser bedient wäre...
