### ISSUE TITLE
Kartenansicht

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#6]
- Umschalten zwischen Listensicht und Kartenansicht über Toolbar/Actionbar. Alles andere bleibt gleich. Suche, Filter....
- für die Playstore Variante wird Google Maps verwendet
- Layout und Navigation ähnlich wie Google Maps

**Comment by IncorporateApps** [comment]
Wie ist der Status hier, sollten wir mit Maps API V2 anfangen? Dann bräuchte man noch ein API_KEY fürs debuggen und eins für live aus der Google API Console. 

Sollten wir auch zusätzlich noch ein Issue für die Erstellung der Pin Grafiken hinzufügen? Folgende Map pins z.B: vegan, vegetarisch, cafe, bio oder was weiss ich noch... Sollte man vorher vielleicht eine Liste mit Pins definieren und diese dort festlegen damit die "Grafikabteilung" Bescheid weisst :)?

**Comment by smeir** [comment]
Ja, ich denke wir sollten mit Maps API V2 anfangen. Ich habe mal die Keys generiert und commited. Der Debugkey funktioniert in jeder App (Debug Build Variant), der Produktivkey nur wenn man mit dem Berlin-Vegan Zertifikat signiert. Ein Beispiel ist im gmaps Branch. Das Beispiel ist einfach nur generiert und testweise ins Menu eingebunden. Diff: https://github.com/Berlin-Vegan/berlin-vegan-guide/compare/development...gmaps
- [AirMapView](https://github.com/airbnb/AirMapView) habe ich evaluiert. Ist ganz nett, aber bringt uns im Zusammenhang mit F-Droid nicht weiter, da AirMapView eine Abhängigkeit zu den PlayServices hat.

Ich versuche die nächsten Tage das Build System  auf Build Flavors umzustellen. Dann hätten wir ein Flavor mit Play Services für den PlayStore und einen Build Flavor für 100% Open Source (F-Droid).

**Comment by smeir** [comment]
Ich habe jetzt im Branch 2 Flavors angelegt, einer mit Google Maps und einen ohne. Ist nicht perfekt, aber ich denke damit können wir starten und später noch optimieren.

**Comment by ces92** [comment]
Vorraussetzung ist #24

**Comment by jmastr** [comment]
Closed by pull request #71

**Comment by jmastr** [comment]
Closed by pull request #71
