### ISSUE TITLE
Einbinden von Icons zu Lokalität-Arten in der Karte

### ISSUE THREAD

**Issue by Robin-siebzehn3** [Berlin-Vegan/berlin-vegan-guide#63]
Hier zur Ansicht, wie die Einbindung der Art-Icons dann in der Karte aussehen könnte. Ich würde gerne auch geschlossene Lokalitäten mit anzeigen, grau dann. Was meint ihr dazu, auch hier einen Hinweis auf "Schließt-bald" einzubinden?

![2-karte_articons_klein](https://cloud.githubusercontent.com/assets/12401165/12267428/5ad7d776-b948-11e5-8a43-a17ee62674be.png)

**Comment by smeir** [comment]
Finde ich super. Auch die geschlossenen Lokalitäten grau anzuzeigen ist sinnvoll und gut. Über die "schließt bald" bin ich mir nicht sicher. Dies intuitiv darzustellen ist nicht einfach, von daher würde ich persönlich diese in der Karte nicht unterscheiden.
