### ISSUE TITLE
Funktion zum Ausblenden geschlossener Lokalitäten

### ISSUE THREAD

**Issue by Robin-siebzehn3** [Berlin-Vegan/berlin-vegan-guide#65]
Ich fände eine solche Funktion, geschlossene Lokalitäten ausblenden zu können, ganz nett, weil zu gewissen Zeiten wirklich viele schon/noch zu haben. Ich persönlich fände es aber hilfreich und wichtig, wenn man jederzeit in der Liste sehen kann, dass dieser Filter eingeschaltet ist. Ich kann gerne einen Entwurf dazu machen, wenn ihr gleicher Meinung seid. Was meint ihr zu dem Thema?

**Comment by ces92** [comment]
Das könnte durch einen Filter realisiert werden?
