### ISSUE TITLE
automatische updates im f-droid store

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#67]
- git magic aus gradle rausziehen

**Comment by jmastr** [comment]
I discussed several approaches with @micuintus and we decided, it would be best, if we could keep the way we are setting the version name (git magic) and try to change the fdroid buildsystem a bit. I wrote a two-liner and they already accepted the change!

See https://gitlab.com/fdroid/fdroidserver/merge_requests/97

I leave this issue open until the next release to see if everything works as expected.

**Comment by jmastr** [comment]
Works as you can see version 2.0.7 (current stable) here: https://f-droid.org/wiki/page/org.berlin_vegan.bvapp :)
