### ISSUE TITLE
Navigation Drawer

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#7]
die Hauptansichten sollen über einer [Navigation Drawer](https://developer.android.com/design/patterns/navigation-drawer.html) umschaltbar sein
- Listenansicht
- Karte
- (Settings)

**Comment by IncorporateApps** [comment]
Das finde ich keine gute Idee bei nur 2 Menupünkten. Wir sollten erstmals mit dem Toolbar arbeiten, es gibt schon eine Material Map Icon
http://materialdesignicons.com/  - Suche map und list

Ansonsten muss man jedes mal 1 Klick mehr betätigen oder swipen. Wir sollten auch unter Settings die Möglichkeit geben ob man im Kartenmodus startet oder nicht.

**Comment by smeir** [comment]
Ja, denke auch bei 2 Einträgen macht es keinen Sinn. Ist eher langfristig, wenn auch noch Einkauf und andere Features wie Termine... dazukommt. Im ersten Schritt können wir die Karte auch erstmal über die Toolbar umschalten.

**Comment by ces92** [comment]
Ist ein doppeltes Ticket zu #24, dort sind Designvorschläge
