### ISSUE TITLE
Kartenübersicht als gleichberechtigte View zur Listenansicht

### ISSUE THREAD

**Issue by micuintus** [Berlin-Vegan/berlin-vegan-guide#76]
Momentan ist die Kartenübersicht abhängig von der Lichtenübersicht (Filter können nur in der Listenübersicht gesetzt werden etc., Standortaktualisierung kann nur in der Listenübersicht angefragt werden), Nahtloses Hin- und Herschalten zw. den Übersichten sollte möglich sein.

**Comment by smeir** [comment]
Ja, ich glaube das hatten wir langfristig auch so geplant. Liste und Karte sind nur 2 unterschiedliche Views auf die gleichen Daten.
