### ISSUE TITLE
Tiles perform badly

### ISSUE THREAD

**Issue by micuintus** [Berlin-Vegan/berlin-vegan-guide#77]
(Google) Tiles performen (bei schlechter Netzverbindung) sehr viel schlechter als die direkte OSM-Variante von OSMdroid

**Comment by jmastr** [comment]
I am currently looking into a solution using CacheManager#downloadAreaAsync. I propose to create a dialog and let the user decide if it is a good time to do the caching.

**Comment by micuintus** [comment]
Cool that sounds interesting!

Furthermore, I also like the idea of @smeir (suggested on the mailinglist) of the user being able to switch between native OSMdroid and the Google tiles OSMdroid variant.
