### ISSUE TITLE
Fotos von Gastronomielokalität einbinden

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#8]
erscheinen in der Detailansicht

**Comment by ces92** [comment]
Wie genau sollen die eingebaut werden? Kann @Robin-siebzehn3 was dazu sagen?

**Comment by Robin-siebzehn3** [comment]
Nein, kann ich nicht wirklich, ich habe das Ticket ja auch gar nicht aufgemacht ^^

**Comment by smeir** [comment]
Das müssen wir uns halt überlegen :-)
